### ISSUE TITLE
Since v2.0.8, importing Sanity UI breaks node scripts

### ISSUE THREAD

**Issue by spacedawwwg** [sanity-io/ui#1236]
Since v2.0.8, importing Sanity UI breaks node scripts scripts e.g.

```SH
import { Card, Stack, ThemeProvider } from '@sanity/ui';
         ^

SyntaxError: The requested module '@sanity/ui' does not provide an export named 'Card'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)
```

It seems in v2.0.8 some exports were removed which seem to be the cause

**To Reproduce**

1. Install > v2.0.7
2. import into a empty TS file (e.g. test.ts)
3. run node script on file `tsx test.ts`

**Expected behavior**

No error importing package

**Which versions of Sanity are you using?**

@sanity/cli (global)     3.34.0 (up to date)
@sanity/code-input        4.1.3 (up to date)
@sanity/icons            2.11.2 (up to date)
@sanity/language-filter   3.2.2 (up to date)
@sanity/ui               2.0.10 (up to date)
@sanity/vision           3.34.0 (up to date)
sanity                   3.34.0 (up to date)

**What operating system are you using?**

MacOS 14.3.1

**Which versions of Node.js / npm are you running?**

10.2.4
v20.11.1

**Comment by spacedawwwg** [comment]
Created a PR to add the node exports back in https://github.com/sanity-io/ui/pull/1237

**Comment by stipsan** [comment]
Hi @spacedawwwg could you give this canary a try?
```bash
npm install @sanity/ui@2.0.11-canary.0
```

**Comment by stipsan** [comment]
@spacedawwwg there's now a stable release you could try https://github.com/sanity-io/ui/releases/tag/v2.0.11

**Comment by spacedawwwg** [comment]
All sorted @stipsan! 🚀
