### ISSUE TITLE
ESM Issue in next-sanity After Upgrading to Version >= 2.11.0

### ISSUE THREAD

**Issue by spencerbeggs** [sanity-io/ui#1246]
In the release for [v2.11.0](https://github.com/sanity-io/ui/commit/1ad5a02320434104dbe15dbd519e2db488fb15e7) a change was made to package.json to "fix: ship ESM with .mjs extensions" by changing the exports. In the change, you ALSO declared `"module": "commonjs"` on line 16. Previously, the `module` type was undeclared, which defaults to `commonjs`. After this change shipped, I see this error when using `next-sanity` in the frontend compile: 

<img width="1001" alt="Screenshot 2024-03-27 at 2 19 22 PM" src="https://github.com/sanity-io/ui/assets/109114/0ac8ece1-a384-4c36-99d6-3ea7e76d4729">

If I manually remove `"module": "commonjs"` or set it to `"module": "module"` in `node_modules/@sanity/ui/package.json`, this error goes away. 

Since you have `exports` properly declared, I don't think you want to declare the type of `module` here and let Node figure it out. Older version will fall back to `commonjs` by default.

**To Reproduce**

1. Install v2.11.0+ in next-sanity
2. Run the dev server

**Expected behavior**

**Screenshots**

**Which versions of Sanity are you using?**

@sanity/cli (global)          3.36.0 (up to date)
@sanity/image-url              1.0.2 (up to date)
@sanity/language-filter        3.2.2 (up to date)
@sanity/portable-text-editor  3.36.0 (up to date)
@sanity/scheduled-publishing   1.3.0 (up to date)
@sanity/ui                    2.0.12 (up to date)
@sanity/vision                3.36.0 (up to date)
sanity                        3.36.0 (up to date)

**What operating system are you using?**

macOS 14.4.1

**Which versions of Node.js / npm are you running?**

10.2.4
v20.11.1

**Comment by stipsan** [comment]
Hi, could you test https://github.com/sanity-io/ui/releases/tag/v2.0.13 and see if it resolves it?

**Comment by markomitranic** [comment]
@stipsan yes, it resolved the issue immediately :) we should probably update other sanity libs that require this one, so that we don't have to hold a pointer to sanity/ui in our package.jsons
